# Generated by Django 4.1.13 on 2024-08-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_remove_showtimes_movie_and_more'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('seats_booked', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theatre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Showtime',
        ),
        migrations.DeleteModel(
            name='Theatre',
        ),
    ]
