# Generated by Django 4.1.13 on 2024-08-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('director', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='showtime',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Movies',
        ),
        migrations.DeleteModel(
            name='Showtimes',
        ),
        migrations.DeleteModel(
            name='Theatres',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
